openapi: 3.0.0
info:
  title: My App API
  description: API documentation for My App
  version: 1.0.0

paths:
  /api/user/{username}:
    get:
      summary: Get a user by username
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  role:
                    type: array
                    items:
                      type: string
        '404':
          description: User not found
