openapi: 3.0.0
info:
  title: Collaborative workflow
  description: API documentation for the Symfony-based task management system, secured with JWT
  version: 1.0.0

servers:
  - url: http://localhost:8000/api
    description: Environnement de développement local (via le serveur PHP Symfony)

paths:
  /api/login_check:
    post:
      summary: Authentification et récupération du jeton JWT
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@test.com
                password:
                  type: string
                  format: password
                  example: 123456
      responses:
        '200':
          description: Jeton JWT généré avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JSON Web Token
                    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQi...
        '401':
          description: Identifiants invalides

  /users:
    get:
      summary: Fetch all users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /users/{id}:
    patch:
      summary: Update a user by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: User updated
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
        '404':
          description: User not found
        '500':
          description: Server error

    delete:
      summary: Delete a user by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user to delete
      responses:
        '204':
          description: User deleted successfully (no content)
        '404':
          description: User not found
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Deletion failed <error message>

  /users/{username}:
    get:
      summary: Fetch a user by username
      security:
        - bearerAuth: []
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
          description: Username of the user to retrieve
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found

  /users/save:
    post:
      summary: Create a new user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: User created
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Creation failed <error message>

  /boards:
    get:
      summary: Fetch all boards
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of boards
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Board'

  /boards/{id}:
    get:
      summary: Fetch a board by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the board to retrieve
      responses:
        '200':
          description: Board found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Board'
        '404':
          description: Board not found
    delete:
      summary: Delete a board by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the board to delete
      responses:
        '204':
          description: Board deleted successfully (no content)
        '404':
          description: Board not found
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Deletion failed <error message>

  /boards/save:
    post:
      summary: Create a new board
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoardDto'
      responses:
        '201':
          description: Board created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Board created
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Creation failed <error message>

  /boards/edit/{id}:
    patch:
      summary: Update an existing board
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the board to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoardDto'
      responses:
        '200':
          description: Board updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Board updated
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
        '404':
          description: Board not found
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Update failed <error message>

  /tasks/{id}:
    get:
      summary: Fetch all tasks for a specific board ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the board to retrieve tasks from
      responses:
        '200':
          description: List of tasks, possibly formatted by TaskFormatter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '404':
          description: Board not found
    delete:
      summary: Delete a task by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the task to delete
      responses:
        '204':
          description: Task deleted successfully (no content)
        '404':
          description: Task not found
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Delete task failed <error message>

  /tasks/save:
    post:
      summary: Create a new task
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDto'
      responses:
        '200':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Task created
        '400':
          description: Validation error
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Creation failed <error message>

  /tasks/edit/{id}:
    patch:
      summary: Update an existing task
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the task to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDto'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Task updated
        '400':
          description: Validation error
        '404':
          description: Task not found
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Update failed <error message>

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        userName:
          type: string
          example: johndoe
        email:
          type: string
          format: email
          example: john@example.com

    UserDto:
      type: object
      required:
        - userName
        - mail
      properties:
        userName:
          type: string
          example: newuser
          description: Username (letters, numbers, underscores only)
        mail:
          type: string
          format: email
          example: newuser@example.com

    Board:
      type: object
      properties:
        id:
          type: integer
          example: 10
        name:
          type: string
          example: My Board
        userRoles:
          type: array
          items:
            $ref: '#/components/schemas/UserRole'
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'

    BoardDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: New Board

    UserRole:
      type: object
      properties:
        id:
          type: integer
          example: 1
        role:
          type: string
          example: admin
        userId:
          type: integer
          example: 5

    TaskState:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: To Do
        order:
          type: integer
          example: 1
          description: The order of the state in the board workflow

    Task:
      type: object
      properties:
        id:
          type: integer
          example: 100
        name:
          type: string
          example: Implement API Documentation
        description:
          type: string
          example: Add all existing routes to the OpenAPI spec.
        state:
          $ref: '#/components/schemas/TaskState'
        boardId:
          type: integer
          example: 10

    TaskDto:
      type: object
      required:
        - name
        - description
        - boardId
      properties:
        name:
          type: string
          example: New Feature
        description:
          type: string
          example: Implement the new user profile page.
        boardId:
          type: integer
          example: 10
          description: The board ID the task belongs to (required for creation)
        stateId:
          type: integer
          example: 1
          description: The ID of the task state (required for updates)