# ===============================================================
# 🏗️ Cloud Build pipeline for Symfony (Cloud Run + Cloud SQL)
# ===============================================================

serviceAccount: projects/symfony-collaborative-workflow/serviceAccounts/cloud-build-sa@symfony-collaborative-workflow.iam.gserviceaccount.com

availableSecrets:
  secretManager:
    - versionName: projects/482952170159/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
    - versionName: projects/482952170159/secrets/APP_SECRET/versions/latest
      env: APP_SECRET

steps:
  # 🧰 1️⃣ Étape : Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'northamerica-northeast1-docker.pkg.dev/symfony-collaborative-workflow/symfony-repo/symfony-image:latest',
        '.'
      ]

  # 🚀 2️⃣ Étape : Push de l’image vers Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-northeast1-docker.pkg.dev/symfony-collaborative-workflow/symfony-repo/symfony-image:latest'
      ]

  # 🌍 3️⃣ Étape : Déploiement sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    secretEnv: ['DATABASE_URL', 'APP_SECRET']
    args:
    - -c
    - |
      gcloud run deploy symfony-web-service \
        --image northamerica-northeast1-docker.pkg.dev/symfony-collaborative-workflow/symfony-repo/symfony-image:latest \
        --platform managed \
        --region northamerica-northeast1 \
        --project symfony-collaborative-workflow \
        --allow-unauthenticated \
        --cpu 1 \
        --memory 512Mi \
        --port 8080 \
        --timeout 300 \
        --concurrency 80 \
        --min-instances 1 \
        --vpc-connector symfony-vpc-connector \
        --service-account cloud-run-db-job@symfony-collaborative-workflow.iam.gserviceaccount.com \
        --set-env-vars APP_ENV=prod \
        --set-secrets DATABASE_URL=DATABASE_URL:latest,APP_SECRET=APP_SECRET:latest

# 🏷️ Liste des images construites
images:
  - 'northamerica-northeast1-docker.pkg.dev/symfony-collaborative-workflow/symfony-repo/symfony-image:latest'

# 🧾 Options de build
options:
  logging: CLOUD_LOGGING_ONLY