version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app_dev
    env_file:
      - .env.local
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=16&charset=utf8"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app:delegated
      - /app/var
    networks:
      - app_network
    command: >
      sh -c "composer install &&
             php bin/console doctrine:migrations:migrate --no-interaction &&
             symfony serve --no-tls --port=8000"

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx_dev
    ports:
      - "8080:80"
    volumes:
      - ./public:/app/public:ro
      - ./docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app_network

  database:
    image: postgres:16-alpine
    container_name: symfony_db_dev
    env_file:
      - .env.local
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # exposé pour outils comme DBeaver ou TablePlus
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  db-data-dev:

networks:
  app_network:
    driver: bridge